module.exports = {
  'accessor-pairs': 'error',
  'array-callback-return': 'error',
  'block-scoped-var': 'off',
  // It's not convenient for classes that are used by frameworks.
  // EG: Angular components' methods used in templates can't be statics.
  'class-methods-use-this': 'error',
  complexity: ['warn',
    10,
  ],
  'consistent-return': 'error',
  curly: 'error',
  'default-case': 'error',
  'dot-location': ['error',
    'property',
  ],
  'dot-notation': 'error',
  eqeqeq: ['error',
    'smart',
  ],
  'guard-for-in': 'off',
  'no-alert': 'error',
  'no-caller': 'error',
  'no-case-declarations': 'error',
  'no-div-regex': 'off',
  'no-else-return': 'error',
  'no-empty-function': ['error', {
    allow: [
      'arrowFunctions',
    ],
  }],
  'no-empty-pattern': 'error',
  'no-eq-null': 'off',
  'no-eval': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-label': 'error',
  'no-fallthrough': 'error',
  'no-floating-decimal': 'error',
  'no-global-assign': 'error',
  'no-implicit-coercion': ['error', {
    boolean: false,
    number: true,
    string: false,
  }],
  'no-implicit-globals': 'error',
  'no-implied-eval': 'error',
  'no-invalid-this': 'off',
  'no-iterator': 'error',
  'no-labels': 'error',
  'no-lone-blocks': 'off',
  'no-loop-func': 'off',
  // Too many numbers are magic according to this one.
  'no-magic-numbers': 'off',
  'no-multi-spaces': 'error',
  'no-multi-str': 'error',
  'no-native-reassign': 'error',
  'no-new-func': 'error',
  'no-new-wrappers': 'error',
  'no-new': 'error',
  'no-octal-escape': 'error',
  'no-octal': 'error',
  'no-param-reassign': 'off',
  'no-proto': 'error',
  // Not useful with const/let
  'no-redeclare': 'off',
  'no-restricted-properties': 'off',
  'no-return-assign': 'error',
  'no-return-await': 'error',
  'no-script-url': 'error',
  'no-self-assign': 'error',
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-throw-literal': 'error',
  'no-unmodified-loop-condition': 'error',
  'no-unused-expressions': 'error',
  'no-unused-labels': 'error',
  'no-useless-call': 'error',
  'no-useless-concat': 'error',
  'no-useless-escape': 'error',
  'no-useless-return': 'error',
  'no-void': 'error',
  'no-warning-comments': 'off',
  'no-with': 'error',
  radix: 'off',
  'require-await': 'error',
  'vars-on-top': 'off',
  'wrap-iife': ['error',
    'inside',
  ],
  yoda: 'error',
};
